import { Theme } from "@/types";
import { getInitParams } from "@/utils/business";

export const offlineTransferFormThemes = {
  white: {
    label: {
      marginBottom: 8,
      fontSize: 14,
      color: "#222",
      textAlign: "left",
      display: "block",
    },
    input: {
      width: "100%",
      padding: "10px 12px",
      borderRadius: 6,
      boxSizing: "border-box",
      border: "1px solid #E5E6EB",
      background: "#fff",
      color: "#222",
      fontSize: 15,
      outline: "none",
      marginBottom: 0,
    },
    inputError: {
      border: "1px solid #ff4d4f",
    },
    select: {
      width: "100%",
      padding: "10px 12px",
      borderRadius: 6,
      border: "1px solid #E5E6EB",
      background: "#fff",
      color: "#222",
      fontSize: 15,
      outline: "none",
    },
    selectError: {
      border: "1px solid #ff4d4f",
    },
    upload: {
      border: "1px dashed #E5E6EB",
      borderRadius: 8,
      background: "#FCFCFD",
      padding: 24,
      textAlign: "center",
      cursor: "pointer",
      minHeight: 120,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      color: "#999",
      fontSize: 15,
    },
    uploadError: {
      border: "1px dashed #ff4d4f",
    },
    fileItem: {
      display: "flex",
      alignItems: "center",
      background: "#F7F8FA",
      borderRadius: 8,
      padding: "12px 16px",
      marginBottom: 8,
      fontSize: 15,
      color: "#222",
      justifyContent: "space-between",
    },
    buttonCancel: {
      background: "#fff",
      color: "#222",
      border: "1px solid #E5E6EB",
      borderRadius: 6,
      padding: "8px 24px",
      fontSize: 15,
      cursor: "pointer",
    },
    buttonSubmit: {
      background: "#1890ff",
      color: "#fff",
      border: "none",
      borderRadius: 6,
      padding: "8px 24px",
      fontSize: 15,
      cursor: "pointer",
      fontWeight: 600,
    },
    removeBtn: {
      background: "#FF4D4F",
      color: "#fff",
      border: "none",
      borderRadius: 6,
      padding: "4px 14px",
      fontSize: 15,
      marginLeft: 16,
      cursor: "pointer",
    },
    error: {
      color: "#ff4d4f",
      fontSize: 13,
      marginTop: 4,
      textAlign: "left",
    },
  },
  dark: {
    label: {
      marginBottom: 8,
      fontSize: 14,
      color: "#fff",
      textAlign: "left",
      display: "block",
    },
    input: {
      width: "100%",
      padding: "10px 12px",
      borderRadius: 6,
      boxSizing: "border-box",
      border: "1px solid #23262F",
      background: "#23262F",
      color: "#fff",
      fontSize: 15,
      outline: "none",
      marginBottom: 0,
    },
    inputError: {
      border: "1px solid #ff4d4f",
    },
    select: {
      width: "100%",
      padding: "10px 12px",
      borderRadius: 6,
      border: "1px solid #23262F",
      background: "#23262F",
      color: "#fff",
      fontSize: 15,
      outline: "none",
    },
    selectError: {
      border: "1px solid #ff4d4f",
    },
    upload: {
      border: "1px dashed #23262F",
      borderRadius: 8,
      background: "#181A20",
      padding: 24,
      textAlign: "center",
      cursor: "pointer",
      minHeight: 120,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      color: "#999",
      fontSize: 15,
    },
    uploadError: {
      border: "1px dashed #ff4d4f",
    },
    fileItem: {
      display: "flex",
      alignItems: "center",
      background: "#23262F",
      borderRadius: 8,
      padding: "12px 16px",
      marginBottom: 8,
      fontSize: 15,
      color: "#fff",
      justifyContent: "space-between",
    },
    buttonCancel: {
      background: "#23262F",
      color: "#fff",
      border: "none",
      borderRadius: 6,
      padding: "8px 24px",
      fontSize: 15,
      cursor: "pointer",
    },
    buttonSubmit: {
      background: "#00E8C6",
      color: "#fff",
      border: "none",
      borderRadius: 6,
      padding: "8px 24px",
      fontSize: 15,
      cursor: "pointer",
      fontWeight: 600,
    },
    removeBtn: {
      background: "#FF4D4F",
      color: "#fff",
      border: "none",
      borderRadius: 6,
      padding: "4px 14px",
      fontSize: 15,
      marginLeft: 16,
      cursor: "pointer",
    },
    error: {
      color: "#ff4d4f",
      fontSize: 13,
      marginTop: 4,
      textAlign: "left",
    },
  },
};

export function getOfflineTransferFormTheme() {
  const theme = getInitParams<Theme>("theme");
  const whiteTheme = theme === Theme.WHITE;
  return whiteTheme
    ? offlineTransferFormThemes.white
    : offlineTransferFormThemes.dark;
}
